version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=clockify-dmoe
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=root
